### ISSUE TITLE
There is an error: when modifying the due date in Todoist, after syncing to Obsidian, the #tdsync tag gets cleared, which causes future syncing with Todoist to fail.

### ISSUE THREAD

**Issue by wsnjh007** [eudennis/ultimate-todoist-sync-for-obsidian-experiment#3]
There is an error: when modifying the due date in Todoist, after syncing to Obsidian, the #tdsync tag gets cleared, which causes future syncing with Todoist to fail.
有个错误，在Todoist上修改截止日期，同步到obsidian后，#tdsync标签会被清楚，导致之后无法和Todoist同步

**Comment by eudennis** [comment]
Can you describe in more detail the steps?

1. You create the task on Obsidian using #tdsync, which show it on Todoist
2. The task is created, but when you change the due date in Todoist, it breaks the task on Obsidian.

Is that right?
Can you confirm which version of the plugin you are using?

**Comment by wsnjh007** [comment]
> Can you describe in more detail the steps?
> 
> 1. You create the task on Obsidian using #tdsync, which show it on Todoist
> 2. The task is created, but when you change the due date in Todoist, it breaks the task on Obsidian.
> 
> Is that right? Can you confirm which version of the plugin you are using?

Yes, it's exactly as you described.
The task is created, but when you change the due date in Todoist, it breaks the task on Obsidian. In Obsidian, the '#tdsync' tag disappears, which causes the task to stop syncing with Todoist. However, if you re-add '#tdsync', the syncing works again.
The version of the plugin is v0.2.0.

I just tested it, and the version v0.3.0 also has this issue.

**Comment by eudennis** [comment]
That's very odd, I was not able to reproduce this. Could you test with a sample task and send me the text before and after it breaks? Maybe you are using something that I'm not.  

Are you using other tags, or changing anything else on Todoist?
When the task is created the first time, on Todoist, do you see the #tdsync tag?

**Comment by wsnjh007** [comment]
> That's very odd, I was not able to reproduce this. Could you test with a sample task and send me the text before and after it breaks? Maybe you are using something that I'm not.
> 
> Are you using other tags, or changing anything else on Todoist? When the task is created the first time, on Todoist, do you see the #tdsync tag?

In Obsidian, when you input "- [ ] test1  #tdsync", it changes to "- [ ] test1  #tdsync %%[tid:: [8493045188](https://todoist.com/app/task/8493045188)]%%" after it takes effect. 

Then, after setting a due date for the task in Todoist, it changes in Obsidian to "- [ ] test1  📅 2024-10-16 $1 %%[tid:: [8493045188](https://todoist.com/app/task/8493045188)]%%."

No other tags or changes were made on Todoist during this process.

**Comment by eudennis** [comment]
k, nice. I was able to reproduce it. I expected a task to be created with a due date, so it doesn't handle it well. 

I will look later today; it should be easy to fix.

Thanks for the support and patience.

**Comment by wsnjh007** [comment]
> k, nice. I was able to reproduce it. I expected a task to be created with a due date, so it doesn't handle it well.
> 
> I will look later today; it should be easy to fix.
> 
> Thanks for the support and patience.

You're welcome, and thank you for your continuous updates—keep up the great work! If you have the capacity, could you also take a look at the question, "Can section information be added to tasks?" Looking forward to seeing this implemented, many thanks!

**Comment by eudennis** [comment]
Hey @wsnjh007 , do you mind testing 3.1? I believe I got the issue fixed. I've tried here and it seems to be fixed

**Comment by wsnjh007** [comment]
> Hey @wsnjh007 , do you mind testing 3.1? I believe I got the issue fixed. I've tried here and it seems to be fixed

Just tested it, and the bug has been fixed. Thank you very much for the update!💐

**Comment by eudennis** [comment]
Awesome! Thanks for taking the time to test it
