### ISSUE TITLE
plugin installation fails with a 404 

### ISSUE THREAD

**Issue by anb-apg** [eudennis/ultimate-todoist-sync-for-obsidian-experiment#5]
When installing this from within obsidian, I get an error. The console talks about a 404, I didn't figure out the correct url. Manual installation works.

**Comment by eudennis** [comment]
Hmm, this is odd. I will take a look, thanks for reporting!

**Comment by eudennis** [comment]
Fixed. The Github file didn't matched the files on the "Release". I've fixed and tested it myself. Thanks for reporting!
