### ISSUE TITLE
Duplicate tasks after opening mobile app w. obsidian sync

### ISSUE THREAD

**Issue by abonhote** [eudennis/ultimate-todoist-sync-for-obsidian-experiment#6]
Hi!

I'm using obsidian sync to sync to my mobile. After not having it open for a while, I started the app yesterday. Your plugin got synced, too. However, it picked up tasks in newly synced files and created new Todoist tasks; it seems that the plugin doesn't now yet that the tasks have been synced already.

Cheers

André

**Comment by eudennis** [comment]
Hmm, I'm not sure if I can reproduce that.

After that first sync, those tasks are duplicated in your Todoist account, correct?
Do you know if the file in Obsidian shows more than one "tid::<task_id>" within the file in Obsidian?

Can you confirm is this behavior happens after the first sync?

**Comment by abonhote** [comment]
Damn, I'm trying to reproduce the behaviour, but I can't. I'll close this for the moment.

**Comment by eudennis** [comment]
No worries, thanks for reporting. I will be aware of that, if anyone finds similar issue or can reproduce it, I can try to find a solution.
