### ISSUE TITLE
Would you be willing to make this plugin compatible with Obsidian Tasks?

### ISSUE THREAD

**Issue by S-H-Y-A** [eudennis/ultimate-todoist-sync-for-obsidian-experiment#7]
I had been looking for the way to sync tasks between Todoist and Obsidian and I found this plugin. I appreciate to you for folking and maintaining this one.
[Obsidian Tasks](https://github.com/obsidian-tasks-group/obsidian-tasks) is one of the most famous obsidian plugins and I also use it.
I think that if this sync plugin recognized tasks's grammar and get compatible for tasks' features such as repeat tasks, complete management of tasks from both obsidian and todoist would become possible.

I would appreciate it if you could make this plugin compatible with Obsidian Tasks.

**Comment by S-H-Y-A** [comment]
Recognizing obsidian tasks' grammar is one of the example way. There may be simpler and easier ways.

**Comment by eudennis** [comment]
Hello, thanks for your support! I surely can take a look on that. But can you expand on what you mean with "obsidian tasks grammar"?

**Comment by S-H-Y-A** [comment]
This is.
https://publish.obsidian.md/tasks/Reference/Task+Formats/About+Task+Formats

**Comment by S-H-Y-A** [comment]
> This is. https://publish.obsidian.md/tasks/Reference/Task+Formats/About+Task+Formats

There are two formats.
 - [Emoji Format](https://publish.obsidian.md/tasks/Reference/Task+Formats/Tasks+Emoji+Format)
 - [Dataview Format](https://publish.obsidian.md/tasks/Reference/Task+Formats/Dataview+Format)

As for Emoji Format, the comcept of explaining data with Emoji is the same.

**Comment by eudennis** [comment]
This plugin supports this already, at least partially - [see this within README](https://github.com/eudennis/ultimate-todoist-sync-for-obsidian-experiment?tab=readme-ov-file#task-format).

Are you looking for something different than that?

Or you mean to use the same standard as the one you've pointed?

**Comment by eudennis** [comment]
Give me some days to take a look at it, Im not familiar on how ObsidianTasks parse data, but within the Todoist Sync plugin it should be straightforward to add new supported formats for the feature it currently supports.

**Comment by eudennis** [comment]
@S-H-Y-A I managed to get it working (at least the due date), it seems to be working as expected. Maybe there is anything specific to your tasks that you're missing?

![image](https://github.com/user-attachments/assets/0ff54796-d064-4f6b-9772-4512cc17ff90)

**Comment by S-H-Y-A** [comment]
I tried some patterns and found that ObsidianTasks ignores all metadata of tasks when Comments(`%% %%`) are included in them. It seems another issue besides obstacles of task managements from both tools.

![Screenshot_20241119-073206.png](https://github.com/user-attachments/assets/e7207050-fbb7-4b99-bb69-4c4638cd0f77)

**Comment by S-H-Y-A** [comment]
that approach sounds

**Comment by S-H-Y-A** [comment]
(I reopend this issue because I had cosed it by mistake.)
> The problem with that approach is that all your tasks would have [tid::0000000] within the task content. Do you think that would work for your case?

That approach sounds good, simple and effective. I think it is not important in general use cases whether task ID is hidden in comment blocks.

**Comment by eudennis** [comment]
I have good news and bad news. This solution didn't work, but I believe I found an alternative. It seems that the date must common at the end, then everything else is accepted as "content". I will try to write a function the moves dates to the end, should work. As a alternative solution you can try to move the %%[tid:<id>]%% the date emojis.

**Comment by eudennis** [comment]
@S-H-Y-A Pushed 0.4.8. Do you mind testing to see if it works for you as it did for me? You will need to enable the "Experimental features", then look for the "Obsidian Tasks Integration" flag. 

I did some testing here; it seems to have worked. This flag just makes sure that whenever a link is added to a new task, it adds before the due date emoji.

**Comment by S-H-Y-A** [comment]
It works fine on my devices. Thank you very much for your work!

**Comment by eudennis** [comment]
Awesome! Thanks for reporting that. I will close here :)
